### ISSUE TITLE
extras dependency resolution error 

### ISSUE THREAD

**Issue by kieranlea** [TheFriendlyCoder/pyjen#20]
Adding pyjen as a dependency for our project creates this error:
`"The 'pyOpenSSL>=0.14; extra == "security"' distribution was not found`

Adding `pyOpenSSL` to requirements.txt seems to fix it. I found some information on this error here: https://github.com/pypa/pip/issues/4957

This seems like a pip bug, but maybe something can be done to work around this in the library.

**Comment by TheFriendlyCoder** [comment]
Fixed in latest build.
